name: testflow

on:
  push:
    branches: [ main ]

env:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build docker containers
        run: docker-compose build 

      - name: run docker containers
        run: |
          echo --- Running test cases ---
          docker-compose -f docker-compose.ci.yml up --exit-code-from backend
          echo --- Completed test cases ---
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: docker-compose build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: publish
        run: docker-compose push
