name: testflow

on:
  pull_request:
    branches: [ main, develop ] 

env: 
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker containers
        run: docker-compose build 

      - name: run docker containers
        run: |
          echo --- Running test cases ---
          docker-compose up --exit-code-from backend
          echo --- Completed test cases ---
